version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravelapp
    ports:
      - "8009:8000"
    volumes:
      - .:/var/www/html
    networks:
      - laravelnet

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - laravelnet
    volumes:
      - dbdata:/var/lib/mysql

networks:
  laravelnet:

volumes:
  dbdata:
